services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - jobdate_net

  backend:
    build:
      context: ./backend
      target: dev
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/src/uploads:/app/src/uploads
    depends_on:
      - mongo
    networks:
      - jobdate_net

  frontend:
    build:
      context: ./frontend
      target: dev
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    networks:
      - jobdate_net

volumes:
  mongo_data:

networks:
  jobdate_net:
    driver: bridge
